name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Geeting
        run: echo "Hello World!"
      - name: Goodbye 
        run: echo "Goodbye"
      - name: Multiline Shell Commands
        run: |
            echo "First Line"
            echo "Second Line"
